Repository NordicSemiconductor/pc-nrfconnect-toolchain-manager, pull requests merged in 2024-06, with the labels that each got.

#248 Update nrfutil toolchain-manager
  Changelog.md
  package-lock.json
  package.json
Labels: doc required, ui not required

#250 Fix/vs code related issues
  Changelog.md
  package.json
  src/Manager/Environment/OpenVsCode.tsx
  src/VsCodeDialog/VsCodeDialog.tsx
  src/VsCodeDialog/vscode.ts
  src/VsCodeDialog/vscodeSlice.ts
Labels: doc not required, ui not required

#251 Fix/overlapping dialog
  Changelog.md
  src/ConfirmationDialog/ConfirmationDialog.tsx
  src/InstallDir/InstallDirDialog.tsx
  src/InstallPackageDialog/InstallPackageDialog.tsx
  src/Manager/Environment/RemoveEnvironmentDialog.tsx
  src/ReduxConfirmDialog/ReduxConfirmDialog.tsx
  src/ToolchainSource/ToolchainSourceDialog.tsx
  src/VsCodeDialog/vscodeSlice.ts
Labels: doc not required, ui not required

#253 Fix: user vscode url to open vscode
  Changelog.md
  src/VsCodeDialog/vscode.ts
Labels: doc not required, ui not required

#249 Feat: add warning for NCS 2.7
  Changelog.md
  src/Manager/Environment/Environment.tsx
  src/Manager/Environment/Install.tsx
Labels: doc not required, ui required

#254 Update toolchain manager cli
  package.json
Labels: doc not required, ui required

#255 Release 1.5.0: prepare
  Changelog.md
  package-lock.json
Labels: doc not required, ui not required
