Repository NordicSemiconductor/pc-nrfconnect-toolchain-manager, pull requests merged in 2024-04, with the labels that each got.

#245 Feat: update shared
  Changelog.md
  package-lock.json
  package.json
  src/index.tsx
Labels: doc not required, ui not required

#244 doc: replace Infocenter links
  Changelog.md
  README.md
  src/FirstInstall/FirstInstallInstructions.tsx
  src/Manager/Environment/ShowFirstSteps.tsx
  src/Manager/PlatformInstructions.tsx
Labels: documentation, doc required

#246 Feat/prepare for m1 support
  Changelog.md
  package-lock.json
  package.json
  src/Manager/Manager.tsx
Labels: doc required, ui required
